services:
  web:
    image: nginx
    container_name: mediblock-web
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro # by default docker search index.html into /usr/share/nginx/html (thx. https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/)