services:
  web:
    image: nginx
    container_name: mediblock-web
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro # by default docker search index.html into /usr/share/nginx/html (thx. https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/)

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mediblock-backend
    ports:
      - 8000:8000 
    volumes:
      - ./backend:/app
      - huggingface_cache:/root/.cache/huggingface # persists the embedding model across container recreations

# huggingface_cache is a named volume internally managed from docker 
volumes:
  huggingface_cache: