
events {
    worker_connections  1024; # default value used 
}

http {
    include       /etc/nginx/mime.types; # necessary otherwise It will throw an Error
    default_type  application/octet-stream; # default type usend when nginx cannot resolve the file type using mime table
    
    server {
        listen 80;
        root /usr/share/nginx/html; 
        index index.html;
    }

}