
events {
    worker_connections  1024; # default value used 
}

http {
    include       /etc/nginx/mime.types; # necessary otherwise It will throw an Error
    default_type  application/octet-stream; # default type usend when nginx cannot resolve the file type using mime table
    
    server {
        listen 80;
        root /usr/share/nginx/html; 
        index index.html;

        # ========= Backend FastAPI ============
        location /api/ {
            proxy_pass http://backend:8000/; # where nginx have to forward the request
            proxy_set_header Host $http_host; # send to the backend the host:port url 
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect http://backend:8000/ /api/; 
        }
    }



}