
export const USERS = [{username: "Marco", score: 1000, difficulty: "facile"},
            {username: "Mario", score: 1240, difficulty: "difficile"},
            {username: "Luigi", score: 1000, difficulty: "difficile"},
            {username: "Marica", score: 800, difficulty: "facile"},
            {username: "Luca", score: 750, difficulty: "facile"},
            {username: "Giovanni", score: 500, difficulty: "difficile"},
            {username: "Umberto", score: 760, difficulty: "facile"},
            {username: "Denise", score: 900, difficulty: "difficile"},
            {username: "Beatrice", score: 880, difficulty: "facile"},
            {username: "Justin", score: 908, difficulty: "difficile"},
            {username: "Federico", score: 605, difficulty: "facile"},
            {username: "Pino", score: 202, difficulty: "difficile"},
            {username: "Lello", score: 810, difficulty: "facile"},
            {username: "Manolo", score: 765, difficulty: "difficile"},
            {username: "Martina", score: 100, difficulty: "facile"},
            {username: "Giuseppe", score: 440, difficulty: "difficile"},
            {username: "Alessio", score: 345, difficulty: "facile"},
            {username: "Leonardo", score: 1500, difficulty: "difficile"},
            {username: "Francesco", score: 870, difficulty: "facile"}
]
